### ISSUE TITLE
Config Bug + Graphic Bug

### ISSUE THREAD

**Issue by Yancha3112** [Tiviacz1337/Warrior-Rage#3]
I use this mod with my friends, I wanted to buff warrior rage using the config, so I put :
killIntervalBetweenNextBonus to 1 - works great
rageDuration tp 60 - works but graphic bug, the bar extends too far to the right of our screen
minimalKillCount to 1 - doesn't work, the minimal kill remains 3 even with the config set to 1

I use WarriorRage-1.19.4-1.4.0.jar

**Comment by Tiviacz1337** [comment]
You have to edit config on server & client, I can't reproduce this issue
