### ISSUE TITLE
enableFireDamage setting has no effect

### ISSUE THREAD

**Issue by 4tw0ne** [Tiviacz1337/Warrior-Rage#8]
Changing the setting, in file "warriorrage-common.toml", of 
	"enableFireDamage = true" 
to
	"enableFireDamage = false" 
does not turn off the 'flame effect' from 'player streak damage'.

Tested in both 1.19.2 and 1.20.1

**Comment by Tiviacz1337** [comment]
it only works when rage is on max lvl
